version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hitman
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hitman"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/hitman
      - RUST_LOG=info
      - SQLX_OFFLINE=false
      - GAME_CODE_LENGTH=6
    depends_on:
      db:
        condition: service_healthy
    command: ./hitman

volumes:
  pgdata: 